const CREATE_TODO = 'CREATE_TODO';
const REMOVE_TODO = 'REMOVE_TODO';
const MARK_TODO_AS_COMPLETED = 'MARK_TODO_AS_COMPLETED';
const LOAD_TODOS_IN_PROGRESS = 'LOAD_TODOS_IN_PROGRESS';
const LOAD_TODOS_SUCCESS = 'LOAD_TODOS_SUCCESS';
const LOAD_TODOS_FAILURE = 'LOAD_TODOS_FAILURE';

module.exports = {
    CREATE_TODO,
    REMOVE_TODO,
    MARK_TODO_AS_COMPLETED,
    LOAD_TODOS_IN_PROGRESS,
    LOAD_TODOS_SUCCESS,
    LOAD_TODOS_FAILURE,
}