// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('create-todo', function () {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function () {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function () {
    await driver.quit();
  })
  it('create-todo', async function () {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1228, height: 775 })
    await driver.findElement(By.id("outlined-required")).click()
    await driver.findElement(By.id("outlined-required")).sendKeys("Title")
    await driver.findElement(By.id("outlined-multiline-static")).click()
    await driver.findElement(By.id("outlined-multiline-static")).sendKeys("Description")
    await driver.findElement(By.id("todo-form__button")).click()
    await driver.findElement(By.id("outlined-required")).click()
    await driver.findElement(By.id("outlined-required")).sendKeys("Title")
    await driver.findElement(By.id("outlined-multiline-static")).click()
    await driver.findElement(By.id("outlined-multiline-static")).sendKeys("Description")
    await driver.findElement(By.id("todo-form__button")).click()
  })
})
