// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('mark-todo-as-completed', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('mark-todo-as-completed', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1228, height: 775 })
    await driver.findElement(By.css(".todo-item__mark")).click()
  })
})
